<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SEW-APAC-619" ignored="0" name="Default test" tests="2" failures="1" timestamp="22 Jul 2021 05:06:11 GMT" time="19.917" errors="0">
  <testcase name="feature" time="14.624" classname="runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="org.junit.ComparisonFailure: expected:&amp;lt;[401]&amp;gt; but was:&amp;lt;[200]&amp;gt;">
      <![CDATA[cucumber.runtime.CucumberException: org.junit.ComparisonFailure: expected:<[401]> but was:<[200]>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at runner.TestRunner.feature(TestRunner.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.junit.ComparisonFailure: expected:<[401]> but was:<[200]>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at stepDefinations.ConnectMe.StepDefinationConnectMeApi.user_validate_API_call_got_success_with_status_code(StepDefinationConnectMeApi.java:56)
	at âœ½.And user validate API call got success  with status  code "200"(ConnectMe/ConnectMe.feature:8)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="4.244" classname="runner.TestRunner"/>
</testsuite> <!-- Default test -->
